version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    entrypoint: ["sh", "-c"]
    command: ["yarn start"]

  postgres:
    image: 'postgres:10.7-alpine'
    container_name: template_postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: template_app,template_app_test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user

volumes:
  postgres_data: